### PR TITLE
better calibration example comments

### PR DESCRIPTION
**Pull request by Manoj-nathwani**
See https://github.com/adafruit/Adafruit_AHRS/issues/14

### CODE REVIEW

**Comment by ladyada** [comment]
hihi i think this comment is also confusing, want to try again?

**Comment by Manoj-nathwani** [comment]
How about changing it to :
```
// see the the LSM6DS_LIS3MDL file in this project to change board to LSM6DS33, LSM6DS3U, LSM6DSOX, etc
```

It's longer but a lot more descriptive

**Comment by ladyada** [comment]
yeah!

**Comment by Manoj-nathwani** [comment]
Updated the PR 🤘

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
great work - its merged :)

**Pull request merged**
